#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_Human_m16

#include "Basic.hpp"

#include "AnimBP_Human_m16_classes.hpp"
#include "AnimBP_Human_m16_parameters.hpp"


namespace SDK
{

// Function AnimBP_Human_m16.AnimBP_Human_m16_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Locomotion                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAnimBP_Human_m16_C::AnimGraph(const struct FPoseLink& Locomotion, struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Human_m16_C", "AnimGraph");

	Params::AnimBP_Human_m16_C_AnimGraph Parms{};

	Parms.Locomotion = std::move(Locomotion);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AnimBP_Human_m16.AnimBP_Human_m16_C.ExecuteUbergraph_AnimBP_Human_m16
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_Human_m16_C::ExecuteUbergraph_AnimBP_Human_m16(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Human_m16_C", "ExecuteUbergraph_AnimBP_Human_m16");

	Params::AnimBP_Human_m16_C_ExecuteUbergraph_AnimBP_Human_m16 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

