#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_Player_TwoHandedConsumable

#include "Basic.hpp"

#include "AnimBP_Player_TwoHandedConsumable_classes.hpp"
#include "AnimBP_Player_TwoHandedConsumable_parameters.hpp"


namespace SDK
{

// Function AnimBP_Player_TwoHandedConsumable.AnimBP_Player_TwoHandedConsumable_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Idle                                                   (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Moving                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Look                                                   (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAnimBP_Player_TwoHandedConsumable_C::AnimGraph(const struct FPoseLink& Idle, const struct FPoseLink& Moving, const struct FPoseLink& Look, struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Player_TwoHandedConsumable_C", "AnimGraph");

	Params::AnimBP_Player_TwoHandedConsumable_C_AnimGraph Parms{};

	Parms.Idle = std::move(Idle);
	Parms.Moving = std::move(Moving);
	Parms.Look = std::move(Look);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AnimBP_Player_TwoHandedConsumable.AnimBP_Player_TwoHandedConsumable_C.ExecuteUbergraph_AnimBP_Player_TwoHandedConsumable
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_Player_TwoHandedConsumable_C::ExecuteUbergraph_AnimBP_Player_TwoHandedConsumable(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Player_TwoHandedConsumable_C", "ExecuteUbergraph_AnimBP_Player_TwoHandedConsumable");

	Params::AnimBP_Player_TwoHandedConsumable_C_ExecuteUbergraph_AnimBP_Player_TwoHandedConsumable Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

