#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_Radio_120

#include "Basic.hpp"

#include "AnimBP_Radio_120_classes.hpp"
#include "AnimBP_Radio_120_parameters.hpp"


namespace SDK
{

// Function AnimBP_Radio_120.AnimBP_Radio_120_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAnimBP_Radio_120_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Radio_120_C", "AnimGraph");

	Params::AnimBP_Radio_120_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AnimBP_Radio_120.AnimBP_Radio_120_C.ExecuteUbergraph_AnimBP_Radio_120
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_Radio_120_C::ExecuteUbergraph_AnimBP_Radio_120(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Radio_120_C", "ExecuteUbergraph_AnimBP_Radio_120");

	Params::AnimBP_Radio_120_C_ExecuteUbergraph_AnimBP_Radio_120 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

