#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_int_chest

#include "Basic.hpp"

#include "AnimBP_int_chest_classes.hpp"
#include "AnimBP_int_chest_parameters.hpp"


namespace SDK
{

// Function AnimBP_int_chest.AnimBP_int_chest_C.Open
// (Public, BlueprintCallable, BlueprintEvent)

void UAnimBP_int_chest_C::Open()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_int_chest_C", "Open");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_int_chest.AnimBP_int_chest_C.ExecuteUbergraph_AnimBP_int_chest
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_int_chest_C::ExecuteUbergraph_AnimBP_int_chest(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_int_chest_C", "ExecuteUbergraph_AnimBP_int_chest");

	Params::AnimBP_int_chest_C_ExecuteUbergraph_AnimBP_int_chest Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AnimBP_int_chest.AnimBP_int_chest_C.Close
// (Public, BlueprintCallable, BlueprintEvent)

void UAnimBP_int_chest_C::Close()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_int_chest_C", "Close");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_int_chest.AnimBP_int_chest_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAnimBP_int_chest_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_int_chest_C", "AnimGraph");

	Params::AnimBP_int_chest_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

