#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ClassicFireAnomaly

#include "Basic.hpp"

#include "BP_ClassicFireAnomaly_classes.hpp"
#include "BP_ClassicFireAnomaly_parameters.hpp"


namespace SDK
{

// Function BP_ClassicFireAnomaly.BP_ClassicFireAnomaly_C.Timeline_1__UpdateFunc
// (BlueprintEvent)

void ABP_ClassicFireAnomaly_C::Timeline_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClassicFireAnomaly_C", "Timeline_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ClassicFireAnomaly.BP_ClassicFireAnomaly_C.Timeline_1__FinishedFunc
// (BlueprintEvent)

void ABP_ClassicFireAnomaly_C::Timeline_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClassicFireAnomaly_C", "Timeline_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ClassicFireAnomaly.BP_ClassicFireAnomaly_C.OnRechargeStateStarted
// (Event, Public, BlueprintEvent)

void ABP_ClassicFireAnomaly_C::OnRechargeStateStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClassicFireAnomaly_C", "OnRechargeStateStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ClassicFireAnomaly.BP_ClassicFireAnomaly_C.OnActiveStateStarted
// (Event, Public, BlueprintEvent)

void ABP_ClassicFireAnomaly_C::OnActiveStateStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClassicFireAnomaly_C", "OnActiveStateStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ClassicFireAnomaly.BP_ClassicFireAnomaly_C.ExecuteUbergraph_BP_ClassicFireAnomaly
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ClassicFireAnomaly_C::ExecuteUbergraph_BP_ClassicFireAnomaly(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClassicFireAnomaly_C", "ExecuteUbergraph_BP_ClassicFireAnomaly");

	Params::BP_ClassicFireAnomaly_C_ExecuteUbergraph_BP_ClassicFireAnomaly Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

