#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DynamicObject_2states_final

#include "Basic.hpp"

#include "AkAudio_structs.hpp"


namespace SDK::Params
{

// Function BP_DynamicObject_2states_final.BP_DynamicObject_2states_final_C.BndEvt__BP_BunkerDoor_Receiver_K2Node_ComponentBoundEvent_0_SignalReceiverComponentReceiveSignature__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_Receiver_K2Node_ComponentBoundEvent_0_SignalReceiverComponentReceiveSignature__DelegateSignature final
{
public:
	class UObject*                                DataObject;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_Receiver_K2Node_ComponentBoundEvent_0_SignalReceiverComponentReceiveSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_Receiver_K2Node_ComponentBoundEvent_0_SignalReceiverComponentReceiveSignature__DelegateSignature");
static_assert(sizeof(BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_Receiver_K2Node_ComponentBoundEvent_0_SignalReceiverComponentReceiveSignature__DelegateSignature) == 0x000008, "Wrong size on BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_Receiver_K2Node_ComponentBoundEvent_0_SignalReceiverComponentReceiveSignature__DelegateSignature");
static_assert(offsetof(BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_Receiver_K2Node_ComponentBoundEvent_0_SignalReceiverComponentReceiveSignature__DelegateSignature, DataObject) == 0x000000, "Member 'BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_Receiver_K2Node_ComponentBoundEvent_0_SignalReceiverComponentReceiveSignature__DelegateSignature::DataObject' has a wrong offset!");

// Function BP_DynamicObject_2states_final.BP_DynamicObject_2states_final_C.BndEvt__BP_BunkerDoor_ReceiverOn_K2Node_ComponentBoundEvent_1_SignalReceiverComponentReceiveSignature__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_ReceiverOn_K2Node_ComponentBoundEvent_1_SignalReceiverComponentReceiveSignature__DelegateSignature final
{
public:
	class UObject*                                DataObject;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_ReceiverOn_K2Node_ComponentBoundEvent_1_SignalReceiverComponentReceiveSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_ReceiverOn_K2Node_ComponentBoundEvent_1_SignalReceiverComponentReceiveSignature__DelegateSignature");
static_assert(sizeof(BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_ReceiverOn_K2Node_ComponentBoundEvent_1_SignalReceiverComponentReceiveSignature__DelegateSignature) == 0x000008, "Wrong size on BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_ReceiverOn_K2Node_ComponentBoundEvent_1_SignalReceiverComponentReceiveSignature__DelegateSignature");
static_assert(offsetof(BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_ReceiverOn_K2Node_ComponentBoundEvent_1_SignalReceiverComponentReceiveSignature__DelegateSignature, DataObject) == 0x000000, "Member 'BP_DynamicObject_2states_final_C_BndEvt__BP_BunkerDoor_ReceiverOn_K2Node_ComponentBoundEvent_1_SignalReceiverComponentReceiveSignature__DelegateSignature::DataObject' has a wrong offset!");

// Function BP_DynamicObject_2states_final.BP_DynamicObject_2states_final_C.ExecuteUbergraph_BP_DynamicObject_2states_final
// 0x0108 (0x0108 - 0x0000)
struct BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(EAkCallbackType CallbackType, class UAkCallbackInfo* CallbackInfo)> Temp_delegate_Variable;                            // 0x0008(0x0010)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(EAkCallbackType CallbackType, class UAkCallbackInfo* CallbackInfo)> Temp_delegate_Variable_1;                          // 0x0028(0x0010)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_ComponentBoundEvent_DataObject_1;           // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEnabled_ReturnValue;                    // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_ComponentBoundEvent_DataObject;             // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class UStaticMeshComponent*>           CallFunc_GetComponentsByTag_ReturnValue;           // 0x0068(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UStaticMeshComponent*>           CallFunc_GetComponentsByTag_ReturnValue_1;         // 0x0078(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item;                           // 0x0088(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item_1;                         // 0x0090(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9A[0x2];                                       // 0x009A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UStaticMeshComponent*>           CallFunc_GetComponentsByTag_ReturnValue_2;         // 0x00A8(0x0010)(ReferenceParm, ContainsInstancedReference)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item_2;                         // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00CD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CE[0x2];                                       // 0x00CE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UStaticMeshComponent*>           CallFunc_GetComponentsByTag_ReturnValue_3;         // 0x00D0(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item_3;                         // 0x00E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x00EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x00ED(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x00EE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EF[0x1];                                       // 0x00EF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x00F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F5[0x3];                                       // 0x00F5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostAkEvent_ReturnValue;                  // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostAkEvent_ReturnValue_1;                // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final) == 0x000008, "Wrong alignment on BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final");
static_assert(sizeof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final) == 0x000108, "Wrong size on BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, EntryPoint) == 0x000000, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, Temp_int_Array_Index_Variable) == 0x000004, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, Temp_delegate_Variable) == 0x000008, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::Temp_delegate_Variable' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, Temp_int_Array_Index_Variable_1) == 0x000018, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, Temp_int_Loop_Counter_Variable) == 0x00001C, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, Temp_int_Array_Index_Variable_2) == 0x000024, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, Temp_delegate_Variable_1) == 0x000028, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::Temp_delegate_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, Temp_int_Loop_Counter_Variable_1) == 0x000038, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, Temp_int_Loop_Counter_Variable_2) == 0x00003C, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Add_IntInt_ReturnValue_1) == 0x000040, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Add_IntInt_ReturnValue_2) == 0x000044, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, Temp_int_Array_Index_Variable_3) == 0x000048, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, K2Node_ComponentBoundEvent_DataObject_1) == 0x000050, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::K2Node_ComponentBoundEvent_DataObject_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_IsEnabled_ReturnValue) == 0x000058, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_IsEnabled_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, K2Node_ComponentBoundEvent_DataObject) == 0x000060, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::K2Node_ComponentBoundEvent_DataObject' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_GetComponentsByTag_ReturnValue) == 0x000068, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_GetComponentsByTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_GetComponentsByTag_ReturnValue_1) == 0x000078, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_GetComponentsByTag_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Array_Get_Item) == 0x000088, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Array_Get_Item_1) == 0x000090, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_IsValid_ReturnValue) == 0x000098, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_IsValid_ReturnValue_1) == 0x000099, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Array_Length_ReturnValue) == 0x00009C, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Array_Length_ReturnValue_1) == 0x0000A0, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_GetComponentsByTag_ReturnValue_2) == 0x0000A8, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_GetComponentsByTag_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Less_IntInt_ReturnValue) == 0x0000B8, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Array_Get_Item_2) == 0x0000C0, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Array_Length_ReturnValue_2) == 0x0000C8, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_IsValid_ReturnValue_2) == 0x0000CC, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000CD, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_GetComponentsByTag_ReturnValue_3) == 0x0000D0, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_GetComponentsByTag_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Array_Get_Item_3) == 0x0000E0, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Array_Length_ReturnValue_3) == 0x0000E8, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_IsValid_ReturnValue_3) == 0x0000EC, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Less_IntInt_ReturnValue_2) == 0x0000ED, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, K2Node_SwitchEnum_CmpSuccess) == 0x0000EE, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, Temp_int_Loop_Counter_Variable_3) == 0x0000F0, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Less_IntInt_ReturnValue_3) == 0x0000F4, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_Add_IntInt_ReturnValue_3) == 0x0000F8, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_PostAkEvent_ReturnValue) == 0x0000FC, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_PostAkEvent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final, CallFunc_PostAkEvent_ReturnValue_1) == 0x000100, "Member 'BP_DynamicObject_2states_final_C_ExecuteUbergraph_BP_DynamicObject_2states_final::CallFunc_PostAkEvent_ReturnValue_1' has a wrong offset!");

// Function BP_DynamicObject_2states_final.BP_DynamicObject_2states_final_C.UserConstructionScript
// 0x0060 (0x0060 - 0x0000)
struct BP_DynamicObject_2states_final_C_UserConstructionScript final
{
public:
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UStaticMeshComponent*>           CallFunc_GetComponentsByTag_ReturnValue;           // 0x0018(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UStaticMeshComponent*>           CallFunc_GetComponentsByTag_ReturnValue_1;         // 0x0040(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item_1;                         // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_DynamicObject_2states_final_C_UserConstructionScript) == 0x000008, "Wrong alignment on BP_DynamicObject_2states_final_C_UserConstructionScript");
static_assert(sizeof(BP_DynamicObject_2states_final_C_UserConstructionScript) == 0x000060, "Wrong size on BP_DynamicObject_2states_final_C_UserConstructionScript");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, Temp_int_Loop_Counter_Variable) == 0x000000, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, CallFunc_Add_IntInt_ReturnValue) == 0x000004, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, Temp_int_Array_Index_Variable) == 0x000008, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, Temp_int_Array_Index_Variable_1) == 0x00000C, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, Temp_int_Loop_Counter_Variable_1) == 0x000010, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, CallFunc_GetComponentsByTag_ReturnValue) == 0x000018, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::CallFunc_GetComponentsByTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, CallFunc_Array_Get_Item) == 0x000028, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, CallFunc_Array_Length_ReturnValue) == 0x000030, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, CallFunc_Add_IntInt_ReturnValue_1) == 0x000034, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, CallFunc_Less_IntInt_ReturnValue) == 0x000038, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, CallFunc_GetComponentsByTag_ReturnValue_1) == 0x000040, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::CallFunc_GetComponentsByTag_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, CallFunc_Array_Get_Item_1) == 0x000050, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, CallFunc_Array_Length_ReturnValue_1) == 0x000058, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_DynamicObject_2states_final_C_UserConstructionScript, CallFunc_Less_IntInt_ReturnValue_1) == 0x00005C, "Member 'BP_DynamicObject_2states_final_C_UserConstructionScript::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");

}

