#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_fur_med_cupboard_2

#include "Basic.hpp"

#include "BP_OpeningContainer_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_fur_med_cupboard_2.BP_fur_med_cupboard_2_C
// 0x0000 (0x0380 - 0x0380)
class ABP_fur_med_cupboard_2_C final : public ABP_OpeningContainer_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_fur_med_cupboard_2_C">();
	}
	static class ABP_fur_med_cupboard_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_fur_med_cupboard_2_C>();
	}
};
static_assert(alignof(ABP_fur_med_cupboard_2_C) == 0x000008, "Wrong alignment on ABP_fur_med_cupboard_2_C");
static_assert(sizeof(ABP_fur_med_cupboard_2_C) == 0x000380, "Wrong size on ABP_fur_med_cupboard_2_C");

}

