#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IntChestItemContainer

#include "Basic.hpp"

#include "BP_IntChestItemContainer_classes.hpp"
#include "BP_IntChestItemContainer_parameters.hpp"


namespace SDK
{

// Function BP_IntChestItemContainer.BP_IntChestItemContainer_C.OnPaintSettingsChanged
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInteractPaint                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_IntChestItemContainer_C::OnPaintSettingsChanged(const bool bInteractPaint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IntChestItemContainer_C", "OnPaintSettingsChanged");

	Params::BP_IntChestItemContainer_C_OnPaintSettingsChanged Parms{};

	Parms.bInteractPaint = bInteractPaint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IntChestItemContainer.BP_IntChestItemContainer_C.ExecuteUbergraph_BP_IntChestItemContainer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_IntChestItemContainer_C::ExecuteUbergraph_BP_IntChestItemContainer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IntChestItemContainer_C", "ExecuteUbergraph_BP_IntChestItemContainer");

	Params::BP_IntChestItemContainer_C_ExecuteUbergraph_BP_IntChestItemContainer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

