#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IAnimatedChest

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_IAnimatedChest.BP_IAnimatedChest_C
// 0x0000 (0x0028 - 0x0028)
class IBP_IAnimatedChest_C final : public IInterface
{
public:
	void Open();
	void Close();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_IAnimatedChest_C">();
	}
	static class IBP_IAnimatedChest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBP_IAnimatedChest_C>();
	}
};
static_assert(alignof(IBP_IAnimatedChest_C) == 0x000008, "Wrong alignment on IBP_IAnimatedChest_C");
static_assert(sizeof(IBP_IAnimatedChest_C) == 0x000028, "Wrong size on IBP_IAnimatedChest_C");

}

