#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_L_cit_room_props_tableLamp_1_final

#include "Basic.hpp"

#include "BP_L_cit_room_props_tableLamp_1_final_classes.hpp"


namespace SDK
{

// Function BP_L_cit_room_props_tableLamp_1_final.BP_L_cit_room_props_tableLamp_1_final_C.PlayFlickeringSound
// (Protected, BlueprintCallable, BlueprintEvent)

void ABP_L_cit_room_props_tableLamp_1_final_C::PlayFlickeringSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_L_cit_room_props_tableLamp_1_final_C", "PlayFlickeringSound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_L_cit_room_props_tableLamp_1_final.BP_L_cit_room_props_tableLamp_1_final_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_L_cit_room_props_tableLamp_1_final_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_L_cit_room_props_tableLamp_1_final_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

