#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_L_gen_lamp_illich_01_cable

#include "Basic.hpp"

#include "BP_L_gen_lamp_illich_01_cable_classes.hpp"


namespace SDK
{

// Function BP_L_gen_lamp_illich_01_cable.BP_L_gen_lamp_illich_01_cable_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_L_gen_lamp_illich_01_cable_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_L_gen_lamp_illich_01_cable_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

