#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_L_ele_wall_lamp_02_final

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_L_ele_wall_lamp_02_final.BP_L_ele_wall_lamp_02_final_C.UserConstructionScript
// 0x0004 (0x0004 - 0x0000)
struct BP_L_ele_wall_lamp_02_final_C_UserConstructionScript final
{
public:
	float                                         RadiusInnerLight;                                  // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_L_ele_wall_lamp_02_final_C_UserConstructionScript) == 0x000004, "Wrong alignment on BP_L_ele_wall_lamp_02_final_C_UserConstructionScript");
static_assert(sizeof(BP_L_ele_wall_lamp_02_final_C_UserConstructionScript) == 0x000004, "Wrong size on BP_L_ele_wall_lamp_02_final_C_UserConstructionScript");
static_assert(offsetof(BP_L_ele_wall_lamp_02_final_C_UserConstructionScript, RadiusInnerLight) == 0x000000, "Member 'BP_L_ele_wall_lamp_02_final_C_UserConstructionScript::RadiusInnerLight' has a wrong offset!");

}

