#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RichTextImageDecorator

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RichTextImageDecorator.BP_RichTextImageDecorator_C
// 0x0000 (0x0030 - 0x0030)
class UBP_RichTextImageDecorator_C final : public URichTextBlockImageDecorator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_RichTextImageDecorator_C">();
	}
	static class UBP_RichTextImageDecorator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_RichTextImageDecorator_C>();
	}
};
static_assert(alignof(UBP_RichTextImageDecorator_C) == 0x000008, "Wrong alignment on UBP_RichTextImageDecorator_C");
static_assert(sizeof(UBP_RichTextImageDecorator_C) == 0x000030, "Wrong size on UBP_RichTextImageDecorator_C");

}

