#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_sign_bus_station_01

#include "Basic.hpp"

#include "BP_sign_bus_station_01_classes.hpp"
#include "BP_sign_bus_station_01_parameters.hpp"


namespace SDK
{

// Function BP_sign_bus_station_01.BP_sign_bus_station_01_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_sign_bus_station_01_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_sign_bus_station_01_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

