#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ToxicCloudAnomaly

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ToxicCloudAnomaly.BP_ToxicCloudAnomaly_C
// 0x0000 (0x0418 - 0x0418)
class ABP_ToxicCloudAnomaly_C final : public AToxicCloudAnomaly
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ToxicCloudAnomaly_C">();
	}
	static class ABP_ToxicCloudAnomaly_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ToxicCloudAnomaly_C>();
	}
};
static_assert(alignof(ABP_ToxicCloudAnomaly_C) == 0x000008, "Wrong alignment on ABP_ToxicCloudAnomaly_C");
static_assert(sizeof(ABP_ToxicCloudAnomaly_C) == 0x000418, "Wrong size on ABP_ToxicCloudAnomaly_C");

}

