#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommonTextScrollStyle

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CommonTextScrollStyle.CommonTextScrollStyle_C
// 0x0000 (0x0040 - 0x0040)
class UCommonTextScrollStyle_C final : public UCommonTextScrollStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CommonTextScrollStyle_C">();
	}
	static class UCommonTextScrollStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCommonTextScrollStyle_C>();
	}
};
static_assert(alignof(UCommonTextScrollStyle_C) == 0x000008, "Wrong alignment on UCommonTextScrollStyle_C");
static_assert(sizeof(UCommonTextScrollStyle_C) == 0x000040, "Wrong size on UCommonTextScrollStyle_C");

}

