#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NavArea_QuestHub_Shevchenko

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NavArea_QuestHub_Shevchenko.NavArea_QuestHub_Shevchenko_C
// 0x0000 (0x0048 - 0x0048)
class UNavArea_QuestHub_Shevchenko_C final : public UNavArea_Scripted
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NavArea_QuestHub_Shevchenko_C">();
	}
	static class UNavArea_QuestHub_Shevchenko_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNavArea_QuestHub_Shevchenko_C>();
	}
};
static_assert(alignof(UNavArea_QuestHub_Shevchenko_C) == 0x000008, "Wrong alignment on UNavArea_QuestHub_Shevchenko_C");
static_assert(sizeof(UNavArea_QuestHub_Shevchenko_C) == 0x000048, "Wrong size on UNavArea_QuestHub_Shevchenko_C");

}

