#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NavArea_ALifeInQuestOut

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NavArea_ALifeInQuestOut.NavArea_ALifeInQuestOut_C
// 0x0000 (0x0048 - 0x0048)
class UNavArea_ALifeInQuestOut_C final : public UNavArea_Scripted
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NavArea_ALifeInQuestOut_C">();
	}
	static class UNavArea_ALifeInQuestOut_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNavArea_ALifeInQuestOut_C>();
	}
};
static_assert(alignof(UNavArea_ALifeInQuestOut_C) == 0x000008, "Wrong alignment on UNavArea_ALifeInQuestOut_C");
static_assert(sizeof(UNavArea_ALifeInQuestOut_C) == 0x000048, "Wrong size on UNavArea_ALifeInQuestOut_C");

}

