#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrefabAsset

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "PrefabAsset_structs.hpp"


namespace SDK
{

// Class PrefabAsset.TickOnlyInEditorActor
// 0x0000 (0x0298 - 0x0298)
class ATickOnlyInEditorActor : public AActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TickOnlyInEditorActor">();
	}
	static class ATickOnlyInEditorActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATickOnlyInEditorActor>();
	}
};
static_assert(alignof(ATickOnlyInEditorActor) == 0x000008, "Wrong alignment on ATickOnlyInEditorActor");
static_assert(sizeof(ATickOnlyInEditorActor) == 0x000298, "Wrong size on ATickOnlyInEditorActor");

// Class PrefabAsset.PrefabRelativePositionCustomPrimitiveDataUpdatingActor
// 0x0008 (0x02A0 - 0x0298)
class APrefabRelativePositionCustomPrimitiveDataUpdatingActor final : public ATickOnlyInEditorActor
{
public:
	uint32                                        CustomDataIndex;                                   // 0x0298(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29C[0x4];                                      // 0x029C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PrefabRelativePositionCustomPrimitiveDataUpdatingActor">();
	}
	static class APrefabRelativePositionCustomPrimitiveDataUpdatingActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<APrefabRelativePositionCustomPrimitiveDataUpdatingActor>();
	}
};
static_assert(alignof(APrefabRelativePositionCustomPrimitiveDataUpdatingActor) == 0x000008, "Wrong alignment on APrefabRelativePositionCustomPrimitiveDataUpdatingActor");
static_assert(sizeof(APrefabRelativePositionCustomPrimitiveDataUpdatingActor) == 0x0002A0, "Wrong size on APrefabRelativePositionCustomPrimitiveDataUpdatingActor");
static_assert(offsetof(APrefabRelativePositionCustomPrimitiveDataUpdatingActor, CustomDataIndex) == 0x000298, "Member 'APrefabRelativePositionCustomPrimitiveDataUpdatingActor::CustomDataIndex' has a wrong offset!");

// Class PrefabAsset.PrefabActor
// 0x0008 (0x02A0 - 0x0298)
class APrefabActor final : public AActor
{
public:
	class UPrefabComponent*                       PrefabComponent;                                   // 0x0298(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	void DestroyPrefabActor(bool bDestroyAttachedChildren);
	bool GetLockSelection();
	void SetLockSelection(bool bInLocked);
	void SetMobility(EComponentMobility InMobility);
	void SetPrefab(class UPrefabAsset* NewPrefab, bool bForceRevertEvenDisconnected);

	class UPrefabAsset* GetPrefab() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PrefabActor">();
	}
	static class APrefabActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<APrefabActor>();
	}
};
static_assert(alignof(APrefabActor) == 0x000008, "Wrong alignment on APrefabActor");
static_assert(sizeof(APrefabActor) == 0x0002A0, "Wrong size on APrefabActor");
static_assert(offsetof(APrefabActor, PrefabComponent) == 0x000298, "Member 'APrefabActor::PrefabComponent' has a wrong offset!");

// Class PrefabAsset.PrefabFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UPrefabFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static class APrefabActor* SpawnPrefab(const class UObject* WorldContextObject, class UPrefabAsset* PrefabAsset, const struct FTransform& SpawnTransform, TArray<class AActor*>* OutSpawnPrefabInstances, bool bSpawnInstancesOnly, ESpawnActorCollisionHandlingMethod CollisionHandlingOverride, class AActor* Owner);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PrefabFunctionLibrary">();
	}
	static class UPrefabFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrefabFunctionLibrary>();
	}
};
static_assert(alignof(UPrefabFunctionLibrary) == 0x000008, "Wrong alignment on UPrefabFunctionLibrary");
static_assert(sizeof(UPrefabFunctionLibrary) == 0x000028, "Wrong size on UPrefabFunctionLibrary");

// Class PrefabAsset.PrefabAsset
// 0x00C8 (0x00F0 - 0x0028)
class UPrefabAsset : public UObject
{
public:
	TMap<class FString, struct FSoftObjectPath>   AssetReferences;                                   // 0x0028(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FSoftObjectPath                        GeneratedBlueprintAssetReference;                  // 0x0078(0x0020)(Edit, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGuid                                  PrefabId;                                          // 0x0098(0x0010)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FString                                 PrefabContent;                                     // 0x00A8(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FString                                 PrefabHash;                                        // 0x00B8(0x0010)(Edit, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         NumActors;                                         // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_CC[0x4];                                       // 0x00CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                PrefabPivot;                                       // 0x00D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UGSCFoliagePrefab*                      FoliagePrefab;                                     // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PrefabAsset">();
	}
	static class UPrefabAsset* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrefabAsset>();
	}
};
static_assert(alignof(UPrefabAsset) == 0x000008, "Wrong alignment on UPrefabAsset");
static_assert(sizeof(UPrefabAsset) == 0x0000F0, "Wrong size on UPrefabAsset");
static_assert(offsetof(UPrefabAsset, AssetReferences) == 0x000028, "Member 'UPrefabAsset::AssetReferences' has a wrong offset!");
static_assert(offsetof(UPrefabAsset, GeneratedBlueprintAssetReference) == 0x000078, "Member 'UPrefabAsset::GeneratedBlueprintAssetReference' has a wrong offset!");
static_assert(offsetof(UPrefabAsset, PrefabId) == 0x000098, "Member 'UPrefabAsset::PrefabId' has a wrong offset!");
static_assert(offsetof(UPrefabAsset, PrefabContent) == 0x0000A8, "Member 'UPrefabAsset::PrefabContent' has a wrong offset!");
static_assert(offsetof(UPrefabAsset, PrefabHash) == 0x0000B8, "Member 'UPrefabAsset::PrefabHash' has a wrong offset!");
static_assert(offsetof(UPrefabAsset, NumActors) == 0x0000C8, "Member 'UPrefabAsset::NumActors' has a wrong offset!");
static_assert(offsetof(UPrefabAsset, PrefabPivot) == 0x0000D0, "Member 'UPrefabAsset::PrefabPivot' has a wrong offset!");
static_assert(offsetof(UPrefabAsset, FoliagePrefab) == 0x0000E8, "Member 'UPrefabAsset::FoliagePrefab' has a wrong offset!");

// Class PrefabAsset.PrefabVariantAsset
// 0x0008 (0x00F8 - 0x00F0)
class UPrefabVariantAsset final : public UPrefabAsset
{
public:
	class UPrefabAsset*                           Parent;                                            // 0x00F0(0x0008)(Edit, ZeroConstructor, EditConst, NoDestructor, AssetRegistrySearchable, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PrefabVariantAsset">();
	}
	static class UPrefabVariantAsset* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrefabVariantAsset>();
	}
};
static_assert(alignof(UPrefabVariantAsset) == 0x000008, "Wrong alignment on UPrefabVariantAsset");
static_assert(sizeof(UPrefabVariantAsset) == 0x0000F8, "Wrong size on UPrefabVariantAsset");
static_assert(offsetof(UPrefabVariantAsset, Parent) == 0x0000F0, "Member 'UPrefabVariantAsset::Parent' has a wrong offset!");

// Class PrefabAsset.PrefabComponent
// 0x0030 (0x0590 - 0x0560)
class UPrefabComponent final : public UPrimitiveComponent
{
public:
	uint8                                         bConnected : 1;                                    // 0x0560(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bLockSelection : 1;                                // 0x0560(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_561[0x7];                                      // 0x0561(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrefabAsset*                           Prefab;                                            // 0x0568(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UBlueprint*                             GeneratedBlueprint;                                // 0x0570(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FPrefabVariantRule>             VariantRulesOverwrite;                             // 0x0578(0x0010)(Edit, BlueprintVisible, ZeroConstructor, AdvancedDisplay, NativeAccessSpecifierPublic)
	uint8                                         bTransient : 1;                                    // 0x0588(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnTemplate, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_589[0x7];                                      // 0x0589(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PrefabComponent">();
	}
	static class UPrefabComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrefabComponent>();
	}
};
static_assert(alignof(UPrefabComponent) == 0x000010, "Wrong alignment on UPrefabComponent");
static_assert(sizeof(UPrefabComponent) == 0x000590, "Wrong size on UPrefabComponent");
static_assert(offsetof(UPrefabComponent, Prefab) == 0x000568, "Member 'UPrefabComponent::Prefab' has a wrong offset!");
static_assert(offsetof(UPrefabComponent, GeneratedBlueprint) == 0x000570, "Member 'UPrefabComponent::GeneratedBlueprint' has a wrong offset!");
static_assert(offsetof(UPrefabComponent, VariantRulesOverwrite) == 0x000578, "Member 'UPrefabComponent::VariantRulesOverwrite' has a wrong offset!");

// Class PrefabAsset.PrefabExporter
// 0x0000 (0x0078 - 0x0078)
class UPrefabExporter : public UExporter
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PrefabExporter">();
	}
	static class UPrefabExporter* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrefabExporter>();
	}
};
static_assert(alignof(UPrefabExporter) == 0x000008, "Wrong alignment on UPrefabExporter");
static_assert(sizeof(UPrefabExporter) == 0x000078, "Wrong size on UPrefabExporter");

// Class PrefabAsset.PrefabLevelExporter
// 0x0010 (0x0088 - 0x0078)
class UPrefabLevelExporter final : public UPrefabExporter
{
public:
	uint8                                         Pad_78[0x10];                                      // 0x0078(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PrefabLevelExporter">();
	}
	static class UPrefabLevelExporter* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrefabLevelExporter>();
	}
};
static_assert(alignof(UPrefabLevelExporter) == 0x000008, "Wrong alignment on UPrefabLevelExporter");
static_assert(sizeof(UPrefabLevelExporter) == 0x000088, "Wrong size on UPrefabLevelExporter");

// Class PrefabAsset.PrefabObjectExporterT3D
// 0x0000 (0x0078 - 0x0078)
class UPrefabObjectExporterT3D final : public UPrefabExporter
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PrefabObjectExporterT3D">();
	}
	static class UPrefabObjectExporterT3D* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrefabObjectExporterT3D>();
	}
};
static_assert(alignof(UPrefabObjectExporterT3D) == 0x000008, "Wrong alignment on UPrefabObjectExporterT3D");
static_assert(sizeof(UPrefabObjectExporterT3D) == 0x000078, "Wrong size on UPrefabObjectExporterT3D");

// Class PrefabAsset.PrefabToolSettings
// 0x0100 (0x0128 - 0x0028)
class UPrefabToolSettings final : public UObject
{
public:
	bool                                          bReplaceActorsWithCreatedPrefab;                   // 0x0028(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAutoIncludeAttachedActorsWhenCreateNewPrefab;     // 0x0029(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bNestedPrefabSupport;                              // 0x002A(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRestorePrefabActorCollapseStatusAfterPIE;         // 0x002B(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCollapseAllPrefabActorsAfterMapOpened;            // 0x002C(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bMoveActorsInWorldAfterSetPrefabPivot;             // 0x002D(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDuplicateNoRevertWithOffset;                      // 0x002E(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2F[0x1];                                       // 0x002F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 NewPrefabNamePattern;                              // 0x0030(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DuplicateLevelForPackagingPostfix;                 // 0x0040(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSaveCurrentLevelBeforeDuplicate;                  // 0x0050(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	EPTUITheme                                    UITheme;                                           // 0x0054(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUpdateAllPrefabActorsWhenOpenMap;                 // 0x0058(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCheckPrefabChangeBeforeUpdateAllPrefabActorsWhenOpenMap; // 0x0059(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableRevertPrefabOnCellLoaded;                   // 0x005A(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUpdateAllPrefabActorsWhenApply;                   // 0x005B(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bApplyToNestedPrefab;                              // 0x005C(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableApplyFromDisconnectedPrefabActor;           // 0x005D(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bTryQuickApplyFirstWhenApply;                      // 0x005E(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAutoAddRemoveVariantActorPrefix;                  // 0x005F(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 VariantActorPrefix;                                // 0x0060(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnablePrefabComponentVisualizer;                  // 0x0070(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPrefabVisualizerType                         PrefabComponentVisualizerType;                     // 0x0071(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDisplayPrefabComponentVisualizerEvenNotSelected;  // 0x0072(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_73[0x1];                                       // 0x0073(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FColor                                 PrefabViewVisualizerColor;                         // 0x0074(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 TargetActorColor;                                  // 0x0078(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 UnLockedConnectedColor;                            // 0x007C(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 LockedConnectedColor;                              // 0x0080(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 UnLockedDisConnectedColor;                         // 0x0084(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 LockedDisConnectedColor;                           // 0x0088(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 UnLockedNoPrefabAssignedColor;                     // 0x008C(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 LockedNoPrefabAssignedColor;                       // 0x0090(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSoftObjectPath                        PrefabMaterialPath;                                // 0x0098(0x0020)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B8[0x30];                                      // 0x00B8(0x0030)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bShadedPrefabViewVisualizer;                       // 0x00E8(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bLockPrefabSelectionByDefault;                     // 0x00E9(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDisableLockPrefabSelectionFeature;                // 0x00EA(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForceApplyPerInstanceVertexColor;                 // 0x00EB(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHideChildActorsInPIEIfHiddenInEditor;             // 0x00EC(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCanToggleChildActorVisibilityInPIE;               // 0x00ED(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_EE[0x1];                                       // 0x00EE(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bIgnoreLayersInPrefab;                             // 0x00EF(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSupportGenerateBlueprint;                         // 0x00F0(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHarvestComponentsWhenGeneratingBlueprint;         // 0x00F1(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseActorNameAsVariableNameWhenGeneratingBlueprint; // 0x00F2(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForceMobilityToMovableWhenGeneratingBlueprint;    // 0x00F3(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F4[0x4];                                       // 0x00F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<TSubclassOf<class AActor>>             IgnoreActorClassesWhenGeneratingBlueprint;         // 0x00F8(0x0010)(Edit, ZeroConstructor, Config, UObjectWrapper, NativeAccessSpecifierPublic)
	TArray<class FName>                           IgnoreActorTagsWhenGeneratingBlueprint;            // 0x0108(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	bool                                          bFlashPrefabWindowForTargetPrefabActor;            // 0x0118(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnablePrefabTextEditor;                           // 0x0119(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDebugMode;                                        // 0x011A(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDisableThumbnailRender;                           // 0x011B(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bShowPrefabInstanceTagInPrefabToolWindow;          // 0x011C(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSkipActorReferenceReplacement;                    // 0x011D(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11E[0x2];                                      // 0x011E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         RealtimeThumbnailThreshold;                        // 0x0120(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bShouldDoApplyAfterGroupActorOperations;           // 0x0124(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_125[0x3];                                      // 0x0125(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PrefabToolSettings">();
	}
	static class UPrefabToolSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrefabToolSettings>();
	}
};
static_assert(alignof(UPrefabToolSettings) == 0x000008, "Wrong alignment on UPrefabToolSettings");
static_assert(sizeof(UPrefabToolSettings) == 0x000128, "Wrong size on UPrefabToolSettings");
static_assert(offsetof(UPrefabToolSettings, bReplaceActorsWithCreatedPrefab) == 0x000028, "Member 'UPrefabToolSettings::bReplaceActorsWithCreatedPrefab' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bAutoIncludeAttachedActorsWhenCreateNewPrefab) == 0x000029, "Member 'UPrefabToolSettings::bAutoIncludeAttachedActorsWhenCreateNewPrefab' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bNestedPrefabSupport) == 0x00002A, "Member 'UPrefabToolSettings::bNestedPrefabSupport' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bRestorePrefabActorCollapseStatusAfterPIE) == 0x00002B, "Member 'UPrefabToolSettings::bRestorePrefabActorCollapseStatusAfterPIE' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bCollapseAllPrefabActorsAfterMapOpened) == 0x00002C, "Member 'UPrefabToolSettings::bCollapseAllPrefabActorsAfterMapOpened' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bMoveActorsInWorldAfterSetPrefabPivot) == 0x00002D, "Member 'UPrefabToolSettings::bMoveActorsInWorldAfterSetPrefabPivot' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bDuplicateNoRevertWithOffset) == 0x00002E, "Member 'UPrefabToolSettings::bDuplicateNoRevertWithOffset' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, NewPrefabNamePattern) == 0x000030, "Member 'UPrefabToolSettings::NewPrefabNamePattern' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, DuplicateLevelForPackagingPostfix) == 0x000040, "Member 'UPrefabToolSettings::DuplicateLevelForPackagingPostfix' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bSaveCurrentLevelBeforeDuplicate) == 0x000050, "Member 'UPrefabToolSettings::bSaveCurrentLevelBeforeDuplicate' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, UITheme) == 0x000054, "Member 'UPrefabToolSettings::UITheme' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bUpdateAllPrefabActorsWhenOpenMap) == 0x000058, "Member 'UPrefabToolSettings::bUpdateAllPrefabActorsWhenOpenMap' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bCheckPrefabChangeBeforeUpdateAllPrefabActorsWhenOpenMap) == 0x000059, "Member 'UPrefabToolSettings::bCheckPrefabChangeBeforeUpdateAllPrefabActorsWhenOpenMap' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bEnableRevertPrefabOnCellLoaded) == 0x00005A, "Member 'UPrefabToolSettings::bEnableRevertPrefabOnCellLoaded' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bUpdateAllPrefabActorsWhenApply) == 0x00005B, "Member 'UPrefabToolSettings::bUpdateAllPrefabActorsWhenApply' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bApplyToNestedPrefab) == 0x00005C, "Member 'UPrefabToolSettings::bApplyToNestedPrefab' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bEnableApplyFromDisconnectedPrefabActor) == 0x00005D, "Member 'UPrefabToolSettings::bEnableApplyFromDisconnectedPrefabActor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bTryQuickApplyFirstWhenApply) == 0x00005E, "Member 'UPrefabToolSettings::bTryQuickApplyFirstWhenApply' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bAutoAddRemoveVariantActorPrefix) == 0x00005F, "Member 'UPrefabToolSettings::bAutoAddRemoveVariantActorPrefix' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, VariantActorPrefix) == 0x000060, "Member 'UPrefabToolSettings::VariantActorPrefix' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bEnablePrefabComponentVisualizer) == 0x000070, "Member 'UPrefabToolSettings::bEnablePrefabComponentVisualizer' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, PrefabComponentVisualizerType) == 0x000071, "Member 'UPrefabToolSettings::PrefabComponentVisualizerType' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bDisplayPrefabComponentVisualizerEvenNotSelected) == 0x000072, "Member 'UPrefabToolSettings::bDisplayPrefabComponentVisualizerEvenNotSelected' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, PrefabViewVisualizerColor) == 0x000074, "Member 'UPrefabToolSettings::PrefabViewVisualizerColor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, TargetActorColor) == 0x000078, "Member 'UPrefabToolSettings::TargetActorColor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, UnLockedConnectedColor) == 0x00007C, "Member 'UPrefabToolSettings::UnLockedConnectedColor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, LockedConnectedColor) == 0x000080, "Member 'UPrefabToolSettings::LockedConnectedColor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, UnLockedDisConnectedColor) == 0x000084, "Member 'UPrefabToolSettings::UnLockedDisConnectedColor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, LockedDisConnectedColor) == 0x000088, "Member 'UPrefabToolSettings::LockedDisConnectedColor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, UnLockedNoPrefabAssignedColor) == 0x00008C, "Member 'UPrefabToolSettings::UnLockedNoPrefabAssignedColor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, LockedNoPrefabAssignedColor) == 0x000090, "Member 'UPrefabToolSettings::LockedNoPrefabAssignedColor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, PrefabMaterialPath) == 0x000098, "Member 'UPrefabToolSettings::PrefabMaterialPath' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bShadedPrefabViewVisualizer) == 0x0000E8, "Member 'UPrefabToolSettings::bShadedPrefabViewVisualizer' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bLockPrefabSelectionByDefault) == 0x0000E9, "Member 'UPrefabToolSettings::bLockPrefabSelectionByDefault' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bDisableLockPrefabSelectionFeature) == 0x0000EA, "Member 'UPrefabToolSettings::bDisableLockPrefabSelectionFeature' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bForceApplyPerInstanceVertexColor) == 0x0000EB, "Member 'UPrefabToolSettings::bForceApplyPerInstanceVertexColor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bHideChildActorsInPIEIfHiddenInEditor) == 0x0000EC, "Member 'UPrefabToolSettings::bHideChildActorsInPIEIfHiddenInEditor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bCanToggleChildActorVisibilityInPIE) == 0x0000ED, "Member 'UPrefabToolSettings::bCanToggleChildActorVisibilityInPIE' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bIgnoreLayersInPrefab) == 0x0000EF, "Member 'UPrefabToolSettings::bIgnoreLayersInPrefab' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bSupportGenerateBlueprint) == 0x0000F0, "Member 'UPrefabToolSettings::bSupportGenerateBlueprint' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bHarvestComponentsWhenGeneratingBlueprint) == 0x0000F1, "Member 'UPrefabToolSettings::bHarvestComponentsWhenGeneratingBlueprint' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bUseActorNameAsVariableNameWhenGeneratingBlueprint) == 0x0000F2, "Member 'UPrefabToolSettings::bUseActorNameAsVariableNameWhenGeneratingBlueprint' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bForceMobilityToMovableWhenGeneratingBlueprint) == 0x0000F3, "Member 'UPrefabToolSettings::bForceMobilityToMovableWhenGeneratingBlueprint' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, IgnoreActorClassesWhenGeneratingBlueprint) == 0x0000F8, "Member 'UPrefabToolSettings::IgnoreActorClassesWhenGeneratingBlueprint' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, IgnoreActorTagsWhenGeneratingBlueprint) == 0x000108, "Member 'UPrefabToolSettings::IgnoreActorTagsWhenGeneratingBlueprint' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bFlashPrefabWindowForTargetPrefabActor) == 0x000118, "Member 'UPrefabToolSettings::bFlashPrefabWindowForTargetPrefabActor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bEnablePrefabTextEditor) == 0x000119, "Member 'UPrefabToolSettings::bEnablePrefabTextEditor' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bDebugMode) == 0x00011A, "Member 'UPrefabToolSettings::bDebugMode' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bDisableThumbnailRender) == 0x00011B, "Member 'UPrefabToolSettings::bDisableThumbnailRender' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bShowPrefabInstanceTagInPrefabToolWindow) == 0x00011C, "Member 'UPrefabToolSettings::bShowPrefabInstanceTagInPrefabToolWindow' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bSkipActorReferenceReplacement) == 0x00011D, "Member 'UPrefabToolSettings::bSkipActorReferenceReplacement' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, RealtimeThumbnailThreshold) == 0x000120, "Member 'UPrefabToolSettings::RealtimeThumbnailThreshold' has a wrong offset!");
static_assert(offsetof(UPrefabToolSettings, bShouldDoApplyAfterGroupActorOperations) == 0x000124, "Member 'UPrefabToolSettings::bShouldDoApplyAfterGroupActorOperations' has a wrong offset!");

// Class PrefabAsset.TerraVolume
// 0x0158 (0x0430 - 0x02D8)
class ATerraVolume final : public AVolume
{
public:
	TArray<uint16>                                CapturedHData;                                     // 0x02D8(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	TMap<struct FIntPoint, uint16>                AppliedAlignHMap;                                  // 0x02E8(0x0050)(NativeAccessSpecifierPrivate)
	TMap<struct FIntPoint, uint16>                AppliedCaptureDeltaHMap;                           // 0x0338(0x0050)(NativeAccessSpecifierPrivate)
	uint8                                         Pad_388[0x8];                                      // 0x0388(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector4                               CurrentBounds;                                     // 0x0390(0x0020)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FIntPoint                              CapturedSize;                                      // 0x03B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FVector                                CapturedBoxExtend0;                                // 0x03B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FVector                                CapturedBoxExtend1;                                // 0x03D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FVector                                CapturedBoxExtend2;                                // 0x03E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FVector                                CapturedBoxExtend3;                                // 0x0400(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	bool                                          bSkipRestoreOnDelete;                              // 0x0418(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_419[0x7];                                      // 0x0419(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ALandscapeProxy*                        CachedLandscape;                                   // 0x0420(0x0008)(ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	bool                                          bApplied;                                          // 0x0428(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	bool                                          bKeepTerrainOnDestruction;                         // 0x0429(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_42A[0x6];                                      // 0x042A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TerraVolume">();
	}
	static class ATerraVolume* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATerraVolume>();
	}
};
static_assert(alignof(ATerraVolume) == 0x000010, "Wrong alignment on ATerraVolume");
static_assert(sizeof(ATerraVolume) == 0x000430, "Wrong size on ATerraVolume");
static_assert(offsetof(ATerraVolume, CapturedHData) == 0x0002D8, "Member 'ATerraVolume::CapturedHData' has a wrong offset!");
static_assert(offsetof(ATerraVolume, AppliedAlignHMap) == 0x0002E8, "Member 'ATerraVolume::AppliedAlignHMap' has a wrong offset!");
static_assert(offsetof(ATerraVolume, AppliedCaptureDeltaHMap) == 0x000338, "Member 'ATerraVolume::AppliedCaptureDeltaHMap' has a wrong offset!");
static_assert(offsetof(ATerraVolume, CurrentBounds) == 0x000390, "Member 'ATerraVolume::CurrentBounds' has a wrong offset!");
static_assert(offsetof(ATerraVolume, CapturedSize) == 0x0003B0, "Member 'ATerraVolume::CapturedSize' has a wrong offset!");
static_assert(offsetof(ATerraVolume, CapturedBoxExtend0) == 0x0003B8, "Member 'ATerraVolume::CapturedBoxExtend0' has a wrong offset!");
static_assert(offsetof(ATerraVolume, CapturedBoxExtend1) == 0x0003D0, "Member 'ATerraVolume::CapturedBoxExtend1' has a wrong offset!");
static_assert(offsetof(ATerraVolume, CapturedBoxExtend2) == 0x0003E8, "Member 'ATerraVolume::CapturedBoxExtend2' has a wrong offset!");
static_assert(offsetof(ATerraVolume, CapturedBoxExtend3) == 0x000400, "Member 'ATerraVolume::CapturedBoxExtend3' has a wrong offset!");
static_assert(offsetof(ATerraVolume, bSkipRestoreOnDelete) == 0x000418, "Member 'ATerraVolume::bSkipRestoreOnDelete' has a wrong offset!");
static_assert(offsetof(ATerraVolume, CachedLandscape) == 0x000420, "Member 'ATerraVolume::CachedLandscape' has a wrong offset!");
static_assert(offsetof(ATerraVolume, bApplied) == 0x000428, "Member 'ATerraVolume::bApplied' has a wrong offset!");
static_assert(offsetof(ATerraVolume, bKeepTerrainOnDestruction) == 0x000429, "Member 'ATerraVolume::bKeepTerrainOnDestruction' has a wrong offset!");

}

