#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S2_ladder_type

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum S2_ladder_type.S2_ladder_type
// NumValues: 0x0006
enum class ES2_ladder_type : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	S2_ladder_MAX                            = 5,
};

}

