#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TutorialRichWidgetDecoratorBP

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TutorialRichWidgetDecoratorBP.TutorialRichWidgetDecoratorBP_C
// 0x0000 (0x0040 - 0x0040)
class UTutorialRichWidgetDecoratorBP_C final : public URichTextBlockWidgetDecorator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TutorialRichWidgetDecoratorBP_C">();
	}
	static class UTutorialRichWidgetDecoratorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTutorialRichWidgetDecoratorBP_C>();
	}
};
static_assert(alignof(UTutorialRichWidgetDecoratorBP_C) == 0x000008, "Wrong alignment on UTutorialRichWidgetDecoratorBP_C");
static_assert(sizeof(UTutorialRichWidgetDecoratorBP_C) == 0x000040, "Wrong size on UTutorialRichWidgetDecoratorBP_C");

}

