#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_AttachImage

#include "Basic.hpp"

#include "W_AttachImage_classes.hpp"
#include "W_AttachImage_parameters.hpp"


namespace SDK
{

// Function W_AttachImage.W_AttachImage_C.ExecuteUbergraph_W_AttachImage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_AttachImage_C::ExecuteUbergraph_W_AttachImage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachImage_C", "ExecuteUbergraph_W_AttachImage");

	Params::W_AttachImage_C_ExecuteUbergraph_W_AttachImage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_AttachImage.W_AttachImage_C.HideImage
// (BlueprintCallable, BlueprintEvent)

void UW_AttachImage_C::HideImage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachImage_C", "HideImage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachImage.W_AttachImage_C.LoadImage
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       Texture                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_AttachImage_C::LoadImage(class UTexture2D* Texture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachImage_C", "LoadImage");

	Params::W_AttachImage_C_LoadImage Parms{};

	Parms.Texture = Texture;

	UObject::ProcessEvent(Func, &Parms);
}

}

