#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_GameHUD

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_GameHUD.W_GameHUD_C
// 0x0000 (0x03D0 - 0x03D0)
class UW_GameHUD_C final : public UPlayerGameHUDView
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_GameHUD_C">();
	}
	static class UW_GameHUD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_GameHUD_C>();
	}
};
static_assert(alignof(UW_GameHUD_C) == 0x000008, "Wrong alignment on UW_GameHUD_C");
static_assert(sizeof(UW_GameHUD_C) == 0x0003D0, "Wrong size on UW_GameHUD_C");

}

