#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_HintTutorialController

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_HintTutorialController.W_HintTutorialController_C
// 0x0010 (0x0370 - 0x0360)
class UW_HintTutorialController_C final : public UHintTutorialController
{
public:
	class UW_HintViewGamepad_C*                   HintViewGamepad;                                   // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_HintViewKeyboard_C*                  HintViewKeyboard;                                  // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_HintTutorialController_C">();
	}
	static class UW_HintTutorialController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_HintTutorialController_C>();
	}
};
static_assert(alignof(UW_HintTutorialController_C) == 0x000008, "Wrong alignment on UW_HintTutorialController_C");
static_assert(sizeof(UW_HintTutorialController_C) == 0x000370, "Wrong size on UW_HintTutorialController_C");
static_assert(offsetof(UW_HintTutorialController_C, HintViewGamepad) == 0x000360, "Member 'UW_HintTutorialController_C::HintViewGamepad' has a wrong offset!");
static_assert(offsetof(UW_HintTutorialController_C, HintViewKeyboard) == 0x000368, "Member 'UW_HintTutorialController_C::HintViewKeyboard' has a wrong offset!");

}

