#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_HintViewKeyboard

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_HintViewKeyboard.W_HintViewKeyboard_C
// 0x0000 (0x0340 - 0x0340)
class UW_HintViewKeyboard_C final : public UHintViewBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_HintViewKeyboard_C">();
	}
	static class UW_HintViewKeyboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_HintViewKeyboard_C>();
	}
};
static_assert(alignof(UW_HintViewKeyboard_C) == 0x000008, "Wrong alignment on UW_HintViewKeyboard_C");
static_assert(sizeof(UW_HintViewKeyboard_C) == 0x000340, "Wrong size on UW_HintViewKeyboard_C");

}

