#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_IdleScreenView

#include "Basic.hpp"

#include "W_IdleScreenView_classes.hpp"
#include "W_IdleScreenView_parameters.hpp"


namespace SDK
{

// Function W_IdleScreenView.W_IdleScreenView_C.ExecuteUbergraph_W_IdleScreenView
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_IdleScreenView_C::ExecuteUbergraph_W_IdleScreenView(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_IdleScreenView_C", "ExecuteUbergraph_W_IdleScreenView");

	Params::W_IdleScreenView_C_ExecuteUbergraph_W_IdleScreenView Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_IdleScreenView.W_IdleScreenView_C.InpActEvt_AnyKey_K2Node_InputKeyEvent_1
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UW_IdleScreenView_C::InpActEvt_AnyKey_K2Node_InputKeyEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_IdleScreenView_C", "InpActEvt_AnyKey_K2Node_InputKeyEvent_1");

	Params::W_IdleScreenView_C_InpActEvt_AnyKey_K2Node_InputKeyEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_IdleScreenView.W_IdleScreenView_C.InpActEvt_SpaceBar_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UW_IdleScreenView_C::InpActEvt_SpaceBar_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_IdleScreenView_C", "InpActEvt_SpaceBar_K2Node_InputKeyEvent_0");

	Params::W_IdleScreenView_C_InpActEvt_SpaceBar_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}

}

