#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PDAArrowButton

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_PDAArrowButton.W_PDAArrowButton_C
// 0x0000 (0x02E0 - 0x02E0)
class UW_PDAArrowButton_C final : public UPDAArrowButton
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_PDAArrowButton_C">();
	}
	static class UW_PDAArrowButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_PDAArrowButton_C>();
	}
};
static_assert(alignof(UW_PDAArrowButton_C) == 0x000008, "Wrong alignment on UW_PDAArrowButton_C");
static_assert(sizeof(UW_PDAArrowButton_C) == 0x0002E0, "Wrong size on UW_PDAArrowButton_C");

}

