#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PlayerStorageData

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_PlayerStorageData.W_PlayerStorageData_C
// 0x0000 (0x0288 - 0x0288)
class UW_PlayerStorageData_C final : public UPlayerStorageData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_PlayerStorageData_C">();
	}
	static class UW_PlayerStorageData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_PlayerStorageData_C>();
	}
};
static_assert(alignof(UW_PlayerStorageData_C) == 0x000008, "Wrong alignment on UW_PlayerStorageData_C");
static_assert(sizeof(UW_PlayerStorageData_C) == 0x000288, "Wrong size on UW_PlayerStorageData_C");

}

