#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_StatisticPage

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_StatisticPage.W_StatisticPage_C
// 0x0008 (0x02A0 - 0x0298)
class UW_StatisticPage_C final : public UPDAPage
{
public:
	class UImage*                                 Image_68;                                          // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_StatisticPage_C">();
	}
	static class UW_StatisticPage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_StatisticPage_C>();
	}
};
static_assert(alignof(UW_StatisticPage_C) == 0x000008, "Wrong alignment on UW_StatisticPage_C");
static_assert(sizeof(UW_StatisticPage_C) == 0x0002A0, "Wrong size on UW_StatisticPage_C");
static_assert(offsetof(UW_StatisticPage_C, Image_68) == 0x000298, "Member 'UW_StatisticPage_C::Image_68' has a wrong offset!");

}

