#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ThreatPointer

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_ThreatPointer.W_ThreatPointer_C
// 0x0010 (0x02D8 - 0x02C8)
class UW_ThreatPointer_C final : public UThreatPointer
{
public:
	class UImage*                                 ThreatGrey;                                        // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               ThreatPointer;                                     // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_ThreatPointer_C">();
	}
	static class UW_ThreatPointer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_ThreatPointer_C>();
	}
};
static_assert(alignof(UW_ThreatPointer_C) == 0x000008, "Wrong alignment on UW_ThreatPointer_C");
static_assert(sizeof(UW_ThreatPointer_C) == 0x0002D8, "Wrong size on UW_ThreatPointer_C");
static_assert(offsetof(UW_ThreatPointer_C, ThreatGrey) == 0x0002C8, "Member 'UW_ThreatPointer_C::ThreatGrey' has a wrong offset!");
static_assert(offsetof(UW_ThreatPointer_C, ThreatPointer) == 0x0002D0, "Member 'UW_ThreatPointer_C::ThreatPointer' has a wrong offset!");

}

