#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_UpgradeItemTooltip

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_UpgradeItemTooltip.W_UpgradeItemTooltip_C
// 0x0010 (0x0378 - 0x0368)
class UW_UpgradeItemTooltip_C final : public UUpgradeItemTooltipWidget
{
public:
	class UImage*                                 Top2;                                              // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Top2_1;                                            // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_UpgradeItemTooltip_C">();
	}
	static class UW_UpgradeItemTooltip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_UpgradeItemTooltip_C>();
	}
};
static_assert(alignof(UW_UpgradeItemTooltip_C) == 0x000008, "Wrong alignment on UW_UpgradeItemTooltip_C");
static_assert(sizeof(UW_UpgradeItemTooltip_C) == 0x000378, "Wrong size on UW_UpgradeItemTooltip_C");
static_assert(offsetof(UW_UpgradeItemTooltip_C, Top2) == 0x000368, "Member 'UW_UpgradeItemTooltip_C::Top2' has a wrong offset!");
static_assert(offsetof(UW_UpgradeItemTooltip_C, Top2_1) == 0x000370, "Member 'UW_UpgradeItemTooltip_C::Top2_1' has a wrong offset!");

}

