#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_UpgradeSlot

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_UpgradeSlot.W_UpgradeSlot_C
// 0x0000 (0x0380 - 0x0380)
class UW_UpgradeSlot_C final : public UUpgradeSlot
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_UpgradeSlot_C">();
	}
	static class UW_UpgradeSlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_UpgradeSlot_C>();
	}
};
static_assert(alignof(UW_UpgradeSlot_C) == 0x000008, "Wrong alignment on UW_UpgradeSlot_C");
static_assert(sizeof(UW_UpgradeSlot_C) == 0x000380, "Wrong size on UW_UpgradeSlot_C");

}

