#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_WorldMapMarker

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_WorldMapMarker.W_WorldMapMarker_C
// 0x0000 (0x0330 - 0x0330)
class UW_WorldMapMarker_C final : public UWorldMapMarker
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_WorldMapMarker_C">();
	}
	static class UW_WorldMapMarker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_WorldMapMarker_C>();
	}
};
static_assert(alignof(UW_WorldMapMarker_C) == 0x000008, "Wrong alignment on UW_WorldMapMarker_C");
static_assert(sizeof(UW_WorldMapMarker_C) == 0x000330, "Wrong size on UW_WorldMapMarker_C");

}

