#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_WorldMapZone

#include "Basic.hpp"

#include "Stalker2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_WorldMapZone.W_WorldMapZone_C
// 0x0000 (0x02B0 - 0x02B0)
class UW_WorldMapZone_C final : public UWorldMapMarkerZone
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_WorldMapZone_C">();
	}
	static class UW_WorldMapZone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_WorldMapZone_C>();
	}
};
static_assert(alignof(UW_WorldMapZone_C) == 0x000008, "Wrong alignment on UW_WorldMapZone_C");
static_assert(sizeof(UW_WorldMapZone_C) == 0x0002B0, "Wrong size on UW_WorldMapZone_C");

}

